<?php

use Phinx\Migration\AbstractMigration;

class AffiliateSeedData extends AbstractMigration
{
    /**
     * Migrate Up.
     */
    public function up()
    {
		$this->execute('insert ignore into `m_affiliate_resources` (`updated_at`, `type`, `group`, `priority`, `title`, `value_type`, `value`, `enabled`) values (NOW(), \'faq\', \'Popular questions\', \'0\', \'What is my affiliate URL\', \'text\', \'Your affiliate URL is <a class=\\"fake-link text-bold\\" href=\\"#\\">{affiliate_link}</a>\', \'true\')');
		$this->execute('insert ignore into `m_affiliate_resources` (`updated_at`, `type`, `group`, `priority`, `title`, `value_type`, `value`, `enabled`) values (NOW(), \'faq\', \'Popular questions\', \'1\', \'How much is my affiliate commission?\', \'text\', \'The commission is calculated as flat **50% recurring** of the total amount of sale. *We bear all the transaction fee on our end.*\\n\\nFor example, for each sale of $97 you get $48.50 per sale per month on a **recurring** basis.\', \'true\')');
		$this->execute('insert ignore into `m_affiliate_resources` (`updated_at`, `type`, `group`, `priority`, `title`, `value_type`, `value`, `enabled`) values (NOW(), \'faq\', \'Popular questions\', \'3\', \'Is it a one time or a recurring commission?\', \'text\', \'All commissions are recurring and you will get 50% of the total amount of sale, month after month, as long as the member you have referred to us continues his/her membership.\', \'true\')');
		$this->execute('insert ignore into `m_affiliate_resources` (`updated_at`, `type`, `group`, `priority`, `title`, `value_type`, `value`, `enabled`) values (NOW(), \'faq\', \'Popular questions\', \'2\', \'What is the payment schedule?\', \'text\', \'ALL Commissions are paid out at the **end of every week**. There is a 7 day holding period after each sale for us to handle refunds, chargebacks, etc. But other than that there is no waiting and you are guaranteed to be be paid on every weekend!\', \'true\')');
		$this->execute('insert ignore into `m_affiliate_resources` (`updated_at`, `type`, `group`, `priority`, `title`, `value_type`, `value`, `enabled`) values (NOW(), \'faq\', \'Popular questions\', \'4\', \'How do you send payment? Is it paypal or check?\', \'text\', \'We dispatch all the affiliate commissions through **Paypal only** at the end of each week.\', \'true\')');
		$this->execute('insert ignore into `m_affiliate_resources` (`updated_at`, `type`, `group`, `priority`, `title`, `value_type`, `value`, `enabled`) values (NOW(), \'faq\', \'Popular questions\', \'6\', \'What is the minimum for payout?\', \'text\', \'The minimum amount for a payout is $10.\', \'true\')');
		$this->execute('insert ignore into `m_affiliate_resources` (`updated_at`, `type`, `group`, `priority`, `title`, `value_type`, `value`, `enabled`) values (NOW(), \'faq\', \'Tracking\', \'7\', \'Is there an alternate affiliate URL?\', \'text\', \'Your main affiliate URL is {affiliate_link}. But alternatively, you can also use {affiliate_link1} if you need an alternate URL.\', \'true\')');
		$this->execute('insert ignore into `m_affiliate_resources` (`updated_at`, `type`, `group`, `priority`, `title`, `value_type`, `value`, `enabled`) values (NOW(), \'faq\', \'Tracking\', \'8\', \'Can I track my signup and traffic?\', \'text\', \'Yes, detailed signup and traffic stats are available in the affiliate area. We also send notification emails (opt-in) when a signup or payments is made from a sale you have referred.\\n\\nIn addition to that you can also install Google Analytics code for detailed hit tracking.\', \'true\')');
		$this->execute('insert ignore into `m_affiliate_resources` (`updated_at`, `type`, `group`, `priority`, `title`, `value_type`, `value`, `enabled`) values (NOW(), \'faq\', \'Tracking\', \'9\', \'How long does my affiliate tracking cookie remain active?\', \'text\', \'The cookie is set for a duration of **1 year**. What this means to you is, that you will get credit for your signups even if the potential buyer closes the browser window or joins after a few weeks or months.\', \'true\')');
		$this->execute('insert ignore into `m_affiliate_resources` (`updated_at`, `type`, `group`, `priority`, `title`, `value_type`, `value`, `enabled`) values (NOW(), \'faq\', \'Tracking\', \'10\', \'Can I link directly to the payment page?\', \'text\', \'Yes, you can definitely link directly to the payment page. The URL for that is {affiliate_link}/pricing.\\n\\nSimilarly, you can link to any page of this site with your affiliate URL in front.\', \'true\')');
		$this->execute('insert ignore into `m_affiliate_resources` (`updated_at`, `type`, `group`, `priority`, `title`, `value_type`, `value`, `enabled`) values (NOW(), \'faq\', \'Promotion\', \'11\', \'What kind of promotion material is available to affiliates?\', \'text\', \'We have a full-fledged affiliate center with over 20+ free affiliate promotion tools. Please see the \\"Promotional tools\\" link in your affiliate are for more details.\', \'true\')');
		$this->execute('insert ignore into `m_affiliate_resources` (`updated_at`, `type`, `group`, `priority`, `title`, `value_type`, `value`, `enabled`) values (NOW(), \'faq\', \'Promotion\', \'12\', \'Can I use the word \\"{site_name}\\" in my Google Adwords?\', \'text\', \'Yes, you can certainly do so. We have no problem with that as long as the ads do not misinterpret anything or promote a competing website.\', \'true\')');
		$this->execute('insert ignore into `m_affiliate_resources` (`updated_at`, `type`, `group`, `priority`, `title`, `value_type`, `value`, `enabled`) values (NOW(), \'faq\', \'Promotion\', \'13\', \'Are there any free or paid bonuses for me to give-away to my list?\', \'text\', \'Yes, we regularly create bonuses and mini-sites for promotion. Please contact us for the list of mini-sites and bonuses that you can send to your list.\', \'true\')');
		$this->execute('insert ignore into `m_affiliate_resources` (`updated_at`, `type`, `group`, `priority`, `title`, `value_type`, `value`, `enabled`) values (NOW(), \'faq\', \'Incentives\', \'14\', \'What is the refer three get free offer?\', \'text\', \'It\\\'s very simple. Just refer three sales in any month and get a **paid {site_name} account** (of similar value) for yourself for free the next month (in addition to your affiliate commissions of course).\', \'true\')');
		$this->execute('insert ignore into `m_affiliate_resources` (`updated_at`, `type`, `group`, `priority`, `title`, `value_type`, `value`, `enabled`) values (NOW(), \'faq\', \'Incentives\', \'15\', \'Are you running any affiliate contests?\', \'text\', \'Yes, we do run affiliate contests for cash prizes all year, especially around holidays like 4th of July, Halloween, Black Friday, etc. We contact all affiliates by email regarding these.\', \'true\')');
		$this->execute('insert ignore into `m_affiliate_resources` (`updated_at`, `type`, `group`, `priority`, `title`, `value_type`, `value`, `enabled`) values (NOW(), \'banners\', \'728x90\', \'16\', \'Video marketing made easy\', \'banner\', \'http://www.articlevideorobot.com/v2/site-assets/affiliates/banners/AVR2-Set1-728by90.gif\', \'true\')');
		$this->execute('insert ignore into `m_affiliate_resources` (`updated_at`, `type`, `group`, `priority`, `title`, `value_type`, `value`, `enabled`) values (NOW(), \'banners\', \'300x250\', \'2\', \'Video marketing made easy\', \'banner\', \'http://www.articlevideorobot.com/v2/site-assets/affiliates/banners/AVR2-Set1-300by250.gif\', \'true\')');
		$this->execute('insert ignore into `m_affiliate_resources` (`updated_at`, `type`, `group`, `priority`, `title`, `value_type`, `value`, `enabled`) values (NOW(), \'banners\', \'728x90\', \'17\', \'50% Discount\', \'banner\', \'http://www.articlevideorobot.com/v2/site-assets/affiliates/banners/AVR2-Set2-728by90.gif\', \'true\')');
		$this->execute('insert ignore into `m_affiliate_resources` (`updated_at`, `type`, `group`, `priority`, `title`, `value_type`, `value`, `enabled`) values (NOW(), \'emails\', \'Promo set #1\', \'18\', \'First email\', \'code\', \'Possible subjects:\\n--\\nArticle Video Robot 2.0 now LIVE\\nHow I instantly convert articles to video\\nNo camera? No problem...\\n\\nbody:\\n--\\nHey {!firstname_fix},\\n\\nToday a new program raved about by THOUSANDS of Internet marketers just went 2.0.\\n\\nIf you\\\'re in a hurry, check this out now:\\n\\nhttp://articlevideorobot.com/hop/50discount\\n\\nYou know how every once in a few years a product comes along and changes the lives of everyone who touches it?\\n\\nThis is one of them.\\n\\nThink about it:\\n\\nIf you were suddenly able to convert articles to videos in seconds, and have them distributed to dozens of video sharing sites at the click of button, that would truly be awesome right?\\n\\nThat\\\'s exactly what this program does.\\n\\nIt\\\'s called \\"Article Video Robot 2.0\\", and it\\\'s going to get your profits soaring like you\\\'ve never imagined.\\n\\nWhen you run this program, it does EVERYTHING for you, including...\\n\\n- Convert articles to amazing videos instantly\\n- Distribute your videos to dozens of video sharing sites\\n- Generate a tsunami of traffic to your website\\n- Get your sales & profits skyrocketing\\n\\nBest part?\\n\\nNo camera or video editing skills required.\\n\\nIt\\\'s truly push button magic - Something you\\\'ve to see to believe.\\n\\nGet the full scoop here:\\n\\nhttp://articlevideorobot.com/hop/50discount\\n\\nCheers!\\nMember\', \'true\')');
		$this->execute('insert ignore into `m_affiliate_resources` (`updated_at`, `type`, `group`, `priority`, `title`, `value_type`, `value`, `enabled`) values (NOW(), \'emails\', \'Promo set #1\', \'19\', \'Second email\', \'code\', \'Possible subjects:\\n--\\nIf you\\\'re struggling to create videos, let this tool do the work for you...\\nThis tool turns words into professional videos at lightning speed...\\nThis tool turns any writer into a professional video creator...\\nGet professional videos at the touch of a button...\\nCreate pro videos in 3 minutes even if you\\\'ve got no video editing experience...\\nYour video creation headaches are over...\\n\\nBody:\\n--\\nHi,\\n\\nI\\\'m writing to you today to tell you about the new release of Article Video Robot 2.0...\\n\\nThe first version of the software was a brilling marketing tool for my business and the second version is even more of a powerhouse...\\n\\nIf you\\\'re not familiar with Article Video Robot, the software uses articles to create stunning videos. Version 2.0 comes with a range of killer features including...\\n\\n- Real people video intros...\\n- More \\\'real sounding\\\' voice overs...\\n- Killer marketing video templates...\\n- Automatic upload and social submission...\\n- Lead capture player with redirection...\\n- And much more...\\n\\nThis really is \\\'la creme de la creme\\\' of automated video creation tools for marketers...\\n\\nhttp://articlevideorobot.com/hop/50discount\\n\\nI know what you\\\'re thinking...\\n\\nThe videos produced by \\\'automated\\\' software like this never look professional enough for you to be happy to associate with your business...\\n\\nThat certainly isn\\\'t the case this time...\\n\\nThe videos created by Article Video Robot 2.0 are awesome. They look and sound so professional that there is no way the viewer would ever imagine that they were created automatically from \\\'an article\\\'...\\n\\nDon\\\'t believe me? Check out the demo videos for yourself. There are tons of awesome examples...\\n\\nhttp://articlevideorobot.com/hop/50discount\\n\\nI\\\'ve already picked up a copy of Article Video Robot 2.0 for my own business. If you\\\'d like to speed up the video creation process for your business, I strongly recommend that you do the same...\\n\\nTo Your Success,\\n\\nCheers!\\nMember\', \'true\')');
		$this->execute('insert ignore into `m_affiliate_resources` (`updated_at`, `type`, `group`, `priority`, `title`, `value_type`, `value`, `enabled`) values (NOW(), \'emails\', \'Promo set #2\', \'20\', \'Second email\', \'code\', \'Subjects:\\n--\\nIf you\\\'re struggling to create videos, let this tool do the work for you...\\nThis tool turns words into professional videos at lightning speed...\\nThis tool turns any writer into a professional video creator...\\nGet professional videos at the touch of a button...\\nCreate pro videos in 3 minutes even if you\\\'ve got no video editing experience...\\nYour video creation headaches are over...\\n\\nBody:\\n--\\nHi,\\n\\nAre you struggling with video marketing?\\n\\nDon\\\'t feel you have the video editing expertise to make anything professional?\\n\\nMaybe you\\\'re not comfortable in front of the camera or even recording your voice?\\n\\nWell, I\\\'m writing to you today to tell you about a new piece of software that can create professional marketing videos for you, even if you\\\'re suffering from one or more of the aforementioned problems...\\n\\nThat software is called Article Video Robot 2.0...\\n\\nhttp://articlevideorobot.com/hop/50discount\\n\\nWith just a few clicks, Article Video Robot 2.0 turns your articles into professional videos...\\n\\nIf you can write (or even copy and paste) then you can create fantastic, interactive videos with Article Video Robot 2.0...\\n\\nThe videos that Article Video Robot 2.0 create are visually stunning and brilliantly interactive. You can select a \\\'real sounding\\\' voice over artist of your choice should you want a guy or girl to read out your article throughout the video...\\n\\nAs well as creating the video, you can also distribute it, all over the internet, from inside the software...\\n\\nAnd that\\\'s just the tip of the iceberg. Check out the demo video for a full range of features...\\n\\nhttp://articlevideorobot.com/hop/50discount\\n\\nThis software has been created by marketers for marketers. These guys understand your needs. If you\\\'re serious about video marketing, I strongly suggest you grab yourself a copy...\\n\\nTo Your Success,\\n\\nCheers!\\nMember\', \'true\')');
		$this->execute('insert ignore into `m_affiliate_resources` (`updated_at`, `type`, `group`, `priority`, `title`, `value_type`, `value`, `enabled`) values (NOW(), \'emails\', \'Promo set #2\', \'21\', \'First email\', \'code\', \'Subjects:\\n--\\nIf you\\\'re struggling to create videos, let this tool do the work for you...\\nThis tool turns words into professional videos at lightning speed...\\nThis tool turns any writer into a professional video creator...\\nGet professional videos at the touch of a button...\\nCreate pro videos in 3 minutes even if you\\\'ve got no video editing experience...\\nYour video creation headaches are over...\\n\\nBody:\\n--\\nHi,\\n\\nYou\\\'re probably aware of the huge power of video marketing...\\n\\nVideo is a great tool to engage, teach and persuade...\\n\\nBut many people struggle to create professional videos because they don\\\'t have video editing knowledge and expertise...\\n\\nToday a new tool was released that enables anyone to create professional videos even if you\\\'ve never touched a piece of video editing software before, it\\\'s called Article Video Robot 2.0...\\n\\nhttp://articlevideorobot.com/hop/50discount\\n\\nArticle Video Robot 2.0 turns articles into professional videos that you\\\'ll be more than happy to call your own...\\n\\nThe videos that this software creates are not only visually stunning, they also come with \\\'real sounding\\\' voice overs...\\n\\nThe results are amazing. But don\\\'t just take my word for it. Check out the demo videos for yourself...\\n\\nhttp://articlevideorobot.com/hop/50discount\\n\\nWhat\\\'s even more outstanding about this software is that you can distribute your videos across multiple online channels in one click. This enables you to put your videos in front of millions of potential eyeballs without even leaving the interface of the software...\\n\\nhttp://articlevideorobot.com/hop/50discount\\n\\nI\\\'d highly suggest you check out Article Video Robot 2.0. Not only does it do the professional stuff for you, it also does all of the grunt work too. There isn\\\'t any other video creation software as complete as this in the marketplace...\\n\\nTo Your Success,\\n\\nCheers!\\nMember\', \'true\')');
		$this->execute('insert ignore into `m_affiliate_resources` (`updated_at`, `type`, `group`, `priority`, `title`, `value_type`, `value`, `enabled`) values (NOW(), \'faq\', \'Incentives\', \'16\', \'Can I get a discount for my list?\', \'text\', \'Here is a 50% discount coupon code that you can send to your list: **\\"{username}-discount\\"** (without quotes)\\n\\nThis special coupon code is linked to your account ({username}). What that means to you is that any person who makes a purchase of {site_name} using this special coupon code will be treated as your referral (making it possible for you to get affiliate commission without people clicking your affiliate links).\\n\\nThis works great on sites like Retailmenot.com, Your Facebook page, Internet marketing forums, in a review or blog post, or in YouTube videos where posting affiliate links is not allowed.\', \'true\')');
		$this->execute('insert ignore into `m_affiliate_resources` (`updated_at`, `type`, `group`, `priority`, `title`, `value_type`, `value`, `enabled`) values (NOW(), \'faq\', \'Popular questions\', \'5\', \'What is the eligibility criteria for becoming an affiliate?\', \'text\', \'Everyone is eligible to become an affiliate of {site_name}. We require all affiliates to have a **verified Paypal account** in order to receive commissions.\', \'true\')');
		$this->execute('insert ignore into `m_affiliate_resources` (`updated_at`, `type`, `group`, `priority`, `title`, `value_type`, `value`, `enabled`) values (NOW(), \'ppc\', \'ad 1\', \'2\', \'ad 1\', \'text\', \'ad 1\', \'true\')');
		$this->execute('insert ignore into `m_affiliate_resources` (`updated_at`, `type`, `group`, `priority`, `title`, `value_type`, `value`, `enabled`) values (NOW(), \'ppc\', \'ad 2\', \'1\', \'ad 2\', \'text\', \'ad 2\', \'true\')');
		$this->execute('insert ignore into `m_affiliate_resources` (`updated_at`, `type`, `group`, `priority`, `title`, `value_type`, `value`, `enabled`) values (NOW(), \'bonuses\', \'giveaways\', null, \'Are there any bonuses to give to my list?\', \'text\', \'Yes, you can find them here\', \'true\')');




    }
}